name: Build
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"
jobs:
  build:
    runs-on: self-hosted
    continue-on-error: false
    defaults:
      run:
        working-directory: ./eggstrain
    steps:
      - uses: actions/checkout@v3
      - name: Install Toolchain
        run: rustup toolchain uninstall stable &&
             rustup toolchain install stable &&
             rustup default stable &&
             rustup component add rustfmt &&
             rustup component add clippy
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Format check
        run: cargo fmt --all -- --check
      - name: Clippy check
        run: cargo clippy --all-targets --all-features
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --codecov --output-path lcov.info
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: lcov.info
          retention-days: 3
      - name: Upload to codecov
        uses: codecov/codecov-action@v3
        with:
          token: be8874e2-10d6-434f-9d52-db6094de31d6
          files: lcov.info
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
